# Generated by Django 4.1.2 on 2022-10-26 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pftest', '0002_correspondencias_habilidades_materias_ocupaciones_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='personas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('email', models.CharField(max_length=100)),
                ('u_educativa', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='resultados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tod', models.CharField(max_length=50)),
                ('tor1', models.CharField(max_length=50)),
                ('tor2', models.CharField(max_length=50)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pftest.personas')),
            ],
        ),
    ]
