# Generated by Django 4.1.2 on 2022-10-26 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pftest', '0004_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personas',
            name='lastname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='personas',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
