# Generated by Django 4.1.2 on 2022-10-26 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pftest', '0005_alter_personas_lastname_alter_personas_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personas',
            name='u_educativa',
        ),
        migrations.CreateModel(
            name='estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('u_educativa', models.CharField(max_length=100)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pftest.personas')),
            ],
        ),
    ]
