# Generated by Django 4.1.2 on 2022-10-26 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pftest', '0006_remove_personas_u_educativa_estudiante'),
    ]

    operations = [
        migrations.DeleteModel(
            name='admin',
        ),
        migrations.DeleteModel(
            name='correspondencias',
        ),
        migrations.RemoveField(
            model_name='resultados',
            name='estudiante',
        ),
        migrations.DeleteModel(
            name='tabla_relacion',
        ),
        migrations.DeleteModel(
            name='tipos_ocupacionales',
        ),
        migrations.DeleteModel(
            name='resultados',
        ),
    ]
