# Generated by Django 4.1.2 on 2022-10-26 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pftest', '0007_delete_admin_delete_correspondencias_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='respuestas_valor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_1', models.IntegerField()),
                ('valor_2', models.IntegerField()),
                ('valor_3', models.IntegerField()),
                ('valor_4', models.IntegerField()),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pftest.estudiante')),
            ],
        ),
        migrations.CreateModel(
            name='respuestas_ocupacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria_ocupacional_1', models.IntegerField()),
                ('categoria_ocupacional_2', models.IntegerField()),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pftest.estudiante')),
            ],
        ),
        migrations.CreateModel(
            name='respuestas_materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materia_1', models.IntegerField()),
                ('materia_2', models.IntegerField()),
                ('materia_3', models.IntegerField()),
                ('materia_4', models.IntegerField()),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pftest.estudiante')),
            ],
        ),
        migrations.CreateModel(
            name='respuestas_habilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habilidad_1', models.IntegerField()),
                ('habilidad_2', models.IntegerField()),
                ('habilidad_3', models.IntegerField()),
                ('habilidad_4', models.IntegerField()),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pftest.estudiante')),
            ],
        ),
    ]
