# Generated by Django 4.1.2 on 2022-10-26 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pftest', '0008_respuestas_valor_respuestas_ocupacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='password',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='username',
        ),
    ]
