# Generated by Django 4.1.2 on 2022-10-26 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pftest', '0009_remove_estudiante_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='persona',
        ),
        migrations.AddField(
            model_name='estudiante',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='lastname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='u_educativa',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='personas',
        ),
    ]
