# Generated by Django 4.1.2 on 2022-10-27 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pftest', '0011_respuestas_q6_respuestas_q5_respuestas_q4_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test_1',
        ),
    ]
