# Generated by Django 4.1.2 on 2022-10-27 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pftest', '0012_delete_test_1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='id',
        ),
        migrations.RemoveField(
            model_name='respuestas_habilidad',
            name='estudiante',
        ),
        migrations.RemoveField(
            model_name='respuestas_materia',
            name='estudiante',
        ),
        migrations.RemoveField(
            model_name='respuestas_ocupacion',
            name='estudiante',
        ),
        migrations.RemoveField(
            model_name='respuestas_q1',
            name='estudiante',
        ),
        migrations.RemoveField(
            model_name='respuestas_q2',
            name='estudiante',
        ),
        migrations.RemoveField(
            model_name='respuestas_q3',
            name='estudiante',
        ),
        migrations.RemoveField(
            model_name='respuestas_q4',
            name='estudiante',
        ),
        migrations.RemoveField(
            model_name='respuestas_q5',
            name='estudiante',
        ),
        migrations.RemoveField(
            model_name='respuestas_q6',
            name='estudiante',
        ),
        migrations.RemoveField(
            model_name='respuestas_valor',
            name='estudiante',
        ),
        migrations.AddField(
            model_name='estudiante',
            name='ci',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
