# Generated by Django 4.1.2 on 2022-10-27 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pftest', '0013_remove_estudiante_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuestas_habilidad',
            name='estudiante',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='pftest.estudiante'),
        ),
        migrations.AddField(
            model_name='respuestas_materia',
            name='estudiante',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='pftest.estudiante'),
        ),
        migrations.AddField(
            model_name='respuestas_ocupacion',
            name='estudiante',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='pftest.estudiante'),
        ),
        migrations.AddField(
            model_name='respuestas_q1',
            name='estudiante',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='pftest.estudiante'),
        ),
        migrations.AddField(
            model_name='respuestas_q2',
            name='estudiante',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='pftest.estudiante'),
        ),
        migrations.AddField(
            model_name='respuestas_q3',
            name='estudiante',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='pftest.estudiante'),
        ),
        migrations.AddField(
            model_name='respuestas_q4',
            name='estudiante',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='pftest.estudiante'),
        ),
        migrations.AddField(
            model_name='respuestas_q5',
            name='estudiante',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='pftest.estudiante'),
        ),
        migrations.AddField(
            model_name='respuestas_q6',
            name='estudiante',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='pftest.estudiante'),
        ),
        migrations.AddField(
            model_name='respuestas_valor',
            name='estudiante',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='pftest.estudiante'),
        ),
    ]
