# Generated by Django 4.1.2 on 2022-10-27 17:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pftest', '0014_respuestas_habilidad_estudiante_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
