# Generated by Django 4.1.2 on 2022-10-27 17:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pftest', '0015_estudiante_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='respuestas_habilidad',
            name='estudiante',
        ),
        migrations.RemoveField(
            model_name='respuestas_materia',
            name='estudiante',
        ),
        migrations.RemoveField(
            model_name='respuestas_ocupacion',
            name='estudiante',
        ),
        migrations.RemoveField(
            model_name='respuestas_q1',
            name='estudiante',
        ),
        migrations.RemoveField(
            model_name='respuestas_q2',
            name='estudiante',
        ),
        migrations.RemoveField(
            model_name='respuestas_q3',
            name='estudiante',
        ),
        migrations.RemoveField(
            model_name='respuestas_q4',
            name='estudiante',
        ),
        migrations.RemoveField(
            model_name='respuestas_q5',
            name='estudiante',
        ),
        migrations.RemoveField(
            model_name='respuestas_q6',
            name='estudiante',
        ),
        migrations.RemoveField(
            model_name='respuestas_valor',
            name='estudiante',
        ),
        migrations.AddField(
            model_name='respuestas_habilidad',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='respuestas_materia',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='respuestas_ocupacion',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='respuestas_q1',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='respuestas_q2',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='respuestas_q3',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='respuestas_q4',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='respuestas_q5',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='respuestas_q6',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='respuestas_valor',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
